// ═══════════════════ Consent Form Templates ═══════════════════

export const CONSENT_TEMPLATES = [
  {
    id: "botox_v2",
    name: "Injektion von Botulinumtoxin A zur Faltenkorrektur",
    title: "Aufklärungsbogen — Botulinumtoxin Faltenkorrektur",
    shortName: "Botox Faltenkorrektur",
    version: "2.0",
    reference: "PO 19/Derma 27 · 10/2016v2 · Thieme Compliance",
    sections: [
      { type: "info", title: "Die Faltenkorrektur", html: `<p>Die Ursachen für Falten im Gesicht liegen im natürlichen Alterungsprozess der Haut und in der individuellen Veranlagung, in äußeren Einflüssen (z.B. Sonneneinstrahlung) sowie in den Lebensgewohnheiten (z.B. Rauchen). Wesentlich zur Faltenbildung trägt auch die mimische Aktivität der feinen, kleinen Muskeln unter der Haut bei, die wir oft unbewusst einsetzen, z.B. beim Stirnrunzeln.</p><p>Störende Falten lassen sich, je nach Art und Ursache, durch verschiedene Methoden korrigieren, deren unterschiedliche Belastungen, Risiken und Erfolgschancen wir Ihnen im Aufklärungsgespräch näher erläutern werden.</p><p>In Ihrem Fall empfehlen wir das Einspritzen von <strong>Botulinumtoxin A</strong> in die Gesichtsmuskeln. Dieses Mittel hemmt die Übertragung von Nervenimpulsen, die das Zusammenziehen der Muskeln auslösen und damit zur Bildung der mimischen Falten beitragen. Je nach Dosierung wird die Bewegung gehemmt oder nur stark eingeschränkt. Da aber lediglich ein Teil der mimischen Muskulatur betroffen ist, entsteht kein maskenhaftes Gesicht.</p><p>In den behandelten Arealen lässt die Muskelanspannung nach, dies führt in den folgenden Tagen zu einer deutlichen Entspannung der Haut und zu einem Rückgang der Falten. Die anderen Gesichtsmuskeln werden nicht beeinflusst. Botulinumtoxin A eignet sich insbesondere zur Verminderung von Stirnfalten, „Zornesfalten" und „Krähenfüßen". Nur bedingt eignet sich Botulinumtoxin A für Falten im mittleren Gesicht, da dann auch die Mimik, wie z.B. Lächeln, beeinträchtigt werden kann. Bei bestimmten Vorerkrankungen (z.B. angeborene Muskelschwäche) kann die Injektion nicht durchgeführt werden. Bitte füllen Sie daher den anhängenden Fragebogen sorgfältig aus.</p><p>Botulinumtoxin A wird seit Langem vor allem zur Behandlung krankhafter Spasmen (z.B. unwillkürlicher Bewegungen der Lid- und Nackenmuskulatur) eingesetzt. Nicht alle Botulinumtoxin-Präparate sind formell zur Behandlung mimischer Muskeln zugelassen. Dies schließt jedoch die Anwendung zur Behandlung von Faltenbildung durch den Arzt außerhalb des Zulassungsbereichs nicht aus, falls Sie sich nach näherer Aufklärung, insbesondere über die bekannten Risiken, dafür entscheiden sollten (Off-Label Use). Unbekannte Risiken lassen sich aber nicht ausschließen, auch besteht möglicherweise keine Haftung seitens der Hersteller.</p><p>Falten, die nicht durch Muskelaktivität (Mimik), sondern durch Hautalterung oder UV-Schädigung eingetreten sind, können durch Laserbehandlung, Eigenfetttransfer oder Unterspritzung mit anderen Füllmaterialien gebessert werden. Manchmal ist auch eine operative Korrektur in Form eines Facelifts, Brauenlifts oder einer Lidstraffung erforderlich.</p>` },
      { type: "info", title: "Kostenübernahme", html: `<p>In der Regel übernimmt die gesetzliche Krankenkasse die Kosten dieser Behandlung und eventuell daraus resultierender behandlungsbedürftiger Komplikationen nicht. Es empfiehlt sich in jedem Fall, die Kostenfragen im Vorfeld mit Ihrem Arzt/Ihrer Krankenkasse zu klären.</p>` },
      { type: "info", title: "Wie erfolgt die Behandlung?", html: `<p>Die ambulante Behandlung erfolgt, indem mit einer dünnen Nadel eine bestimmte Menge Botulinumtoxin A exakt an den Stellen im Gesicht eingespritzt wird, die dafür angezeigt sind. Der Schmerz, der beim Einspritzen entsteht, ist mit dem eines Mückenstichs vergleichbar. Bei besonders schmerzempfindlichen Patienten ist zur Betäubung der Einstichstelle das Auftragen einer Betäubungscreme möglich, diese muss jedoch ca. 20 Minuten einwirken.</p><p>Während der Schwangerschaft und Stillzeit, bei neuromuskulären Erkrankungen wie z.B. Myasthenia gravis (schwere, allgemeine Muskelschwäche), Lidheberschwäche, vorliegender Blutgerinnungsstörung, bekannter Überempfindlichkeit gegenüber Botulinumtoxin oder Humanalbumin (Bluteiweiß) sollte eine Behandlung mit Botulinumtoxin nur nach sorgfältiger Abwägung möglicher Risiken erfolgen.</p>` },
      { type: "info", title: "Risiken und mögliche Komplikationen", html: `<p>Trotz aller Sorgfalt kann es zu – u.U. auch lebensbedrohlichen – Komplikationen kommen, die weitere Behandlungsmaßnahmen/Operationen erfordern. Die Häufigkeitsangaben sind eine allgemeine Einschätzung und sollen helfen, die Risiken untereinander zu gewichten.</p><ul><li>Unmittelbar nach der Injektion kann sich an der Injektionsstelle ein kleiner <strong>Bluterguss</strong> (Hämatom) bilden, der sich durch Make-up abdecken lässt und sich nach einigen Tagen, selten erst nach 2–3 Wochen, zurückbildet. Patienten, die Medikamente zur Beeinflussung der Blutgerinnung nehmen, müssen mit einer verstärkten Hämatombildung rechnen.</li><li>Verteilt sich die Substanz im Gewebe, kann es vorübergehend zum <strong>Hängen des Oberlids oder der Braue</strong> kommen. Bei der Behandlung von Krähenfüßen kann eine Verteilung der Substanz im Augenbereich vorübergehende <strong>Sehstörungen</strong> (Doppelbilder) verursachen. Diese Erscheinungen verschwinden innerhalb einiger Wochen wieder.</li><li><strong>Funktionsbeeinträchtigungen von Nerven</strong> (Missempfindungen, Gefühlsstörungen), die nur vorübergehend sind und sich von selbst innerhalb einiger Wochen bessern.</li><li>Botulinumtoxin-Präparate enthalten geringe Mengen an menschlichem Bluteiweiß. Das Risiko, sich durch die Verabreichung der Präparate zu <strong>infizieren</strong> (z.B. mit Hepatitis, AIDS), ist jedoch äußerst unwahrscheinlich.</li><li>Bei <strong>Allergie oder Überempfindlichkeit</strong> (z.B. gegen Medikamente, Betäubungsmittel, Desinfektionsmittel, Latex) können vorübergehend Schwellung, Juckreiz, Niesen, Hautausschlag, Kopfschmerzen, Schwindel, Erbrechen und ähnliche leichtere Reaktionen auftreten. <strong>Stärkere Reaktionen</strong> können zu einem akuten <strong>Kreislaufschock</strong> führen, der intensivmedizinische Maßnahmen erfordert. Sehr selten sind schwerwiegende, u.U. bleibende Schäden (z.B. Organversagen, Hirnschädigung, Lähmungen).</li><li>Als weitere <strong>seltene Nebenwirkungen</strong> können auftreten: leichtes Unwohlsein, Müdigkeit, Gliederschmerzen, Mund-, Schleimhaut- und Augentrockenheit, Schwund von Muskeln, in die das Botulinumtoxin A eingespritzt wurde, Infektion an der Injektionsstelle und Pigmentverschiebungen der Haut.</li><li>Bei Vorliegen einer Schwangerschaft sollte ganz auf eine Botulinumtoxin-Behandlung verzichtet werden.</li></ul>` },
      { type: "info", title: "Erfolgsaussichten", html: `<p>Eine erste Wirkung der Behandlung ist nach ca. 1–3 Tagen sichtbar, die maximal erreichbare nach ca. 1–2 Wochen. Die Wirkung der Injektion hält bei den meisten Patienten ca. 3–6 Monate an, nach wiederholter Anwendung von Botulinumtoxin A verlängert sich die Wirkdauer oft. Extrem selten bilden sich Antikörper gegen den Wirkstoff, wodurch es zu einem schnelleren Abbau bis hin zum Wirkverlust kommt.</p><p>Ein zufriedenstellendes Behandlungsergebnis kann <strong>nicht garantiert</strong> werden. In Einzelfällen kann trotz sorgfältiger und korrekter Durchführung des Eingriffs das angestrebte Ergebnis verfehlt und der bestehende Zustand sogar verschlechtert werden.</p>` },
      { type: "info", title: "Bitte unbedingt beachten!", html: `<p><strong>Vor der Behandlung:</strong> Bitte legen Sie einschlägige Unterlagen wie z.B. Ausweise/Pässe (Allergie, Mutterschaft, Röntgen, Implantate etc.), Befunde und Bilder – soweit vorhanden – vor. Bitte geben Sie im Fragebogen alle Medikamente an, die Sie derzeit einnehmen. Dies betrifft vor allem <strong>blutgerinnungshemmende Medikamente</strong> (z.B. Marcumar®, Aspirin®, Plavix®, Iscover®, Pradaxa®, Xarelto®, Eliquis® etc.). Das Gesicht bitte gründlich reinigen und nicht schminken. Bitte weisen Sie uns unbedingt darauf hin, wenn Sie an einer <strong>Allergie</strong> leiden oder eine <strong>Unverträglichkeit</strong> besteht.</p><p><strong>Nach der Behandlung:</strong> Tragen Sie bitte erst wieder Make-up auf, wenn die Einstichstellen nicht mehr bluten. Am Tag der Injektion sollten Sie keinen Sport treiben und sich auch keiner kosmetischen Gesichtsbehandlung unterziehen.</p>` },
    ],
    questions: [
      { id: "q1_medikamente", label: "Werden regelmäßig oder derzeit Medikamente eingenommen?", details: "(z.B. gerinnungshemmende Mittel, Schmerzmittel, Herz-/Kreislauf-Medikamente, Hormonpräparate, Schlaf- oder Beruhigungsmittel, Antidiabetika)", followUp: "Wenn ja, welche?" },
      { id: "q2_allergie", label: "Besteht eine Allergie wie Heuschnupfen oder allergisches Asthma oder eine Unverträglichkeit bestimmter Substanzen?", details: "(z.B. Medikamente, Latex, Desinfektionsmittel, Betäubungsmittel, Röntgenkontrastmittel, Jod, Pflaster, Pollen)", followUp: "Wenn ja, welche?" },
      { id: "q3_blutungsneigung", label: "Besteht bei Ihnen oder in Ihrer Blutsverwandtschaft eine erhöhte Blutungsneigung?", details: "(z.B. häufig Nasen-/Zahnfleischbluten, blaue Flecken, Nachbluten nach Operationen)" },
      { id: "q4_infektionskrankheit", label: "Besteht/Bestand eine Infektionskrankheit?", details: "(z.B. Hepatitis, Tuberkulose, HIV/AIDS)", followUp: "Wenn ja, welche?" },
      { id: "q5_herzkreislauf", label: "Besteht/Bestand eine Herz-Kreislauf-Erkrankung?", details: "(z.B. Herzfehler, Herzklappenfehler, Angina pectoris, Herzinfarkt, Schlaganfall, Rhythmusstörungen, Herzmuskelentzündung, hoher Blutdruck)", followUp: "Wenn ja, welche?" },
      { id: "q6_nervensystem", label: "Besteht/Bestand eine Erkrankung des Nervensystems?", details: "(z.B. Lähmungen, Krampfleiden [Epilepsie], chronische Schmerzen)", followUp: "Wenn ja, welche?" },
      { id: "q7_psychisch", label: "Liegt eine psychische Erkrankung vor?", details: "(z.B. Depression, Borderline-Syndrom)", followUp: "Wenn ja, welche?" },
      { id: "q8_erbkrankheit", label: "Besteht eine Erbkrankheit (z.B. angeborene Muskelschwäche, Myasthenie) oder sind ähnliche Erkrankungen in der Blutsverwandtschaft bekannt?", followUp: "Wenn ja, welche?" },
      { id: "q9_wundheilung", label: "Kam es schon einmal zu Wundheilungsstörungen?", details: "(z.B. Entzündung, Abszess, Fistel)" },
      { id: "q10_narbenwucherung", label: "Kam es schon einmal zu einer Narbenwucherung?", details: "(z.B. Keloid)" },
      { id: "q11_lichtempfindlichkeit", label: "Liegt eine verstärkte Lichtempfindlichkeit und/oder eine Neigung zu Pigmentstörungen vor?" },
      { id: "q12_lippenherpes", label: "Treten immer wieder Lippenbläschen (Herpesinfektion) auf?" },
      { id: "q13_botox_vorher", label: "Erfolgten früher schon einmal Einspritzungen von Botulinumtoxin A?", followUp: "Wenn ja, gab es dabei Komplikationen?", subQuestion: true },
      { id: "q14_gesichts_op", label: "Gab es bereits Operationen im Gesichtsbereich?", followUp: "Wenn ja, welche?" },
      { id: "q15_tabak", label: "Regelmäßiger Tabakkonsum?", followUp: "Wenn ja, was und wie viel?" },
    ],
    additionalQuestionsWomen: [
      { id: "zf1_schwanger", label: "Könnten Sie schwanger sein?" },
      { id: "zf2_stillen", label: "Stillen Sie?" },
    ],
    consentText: "Den Aufklärungsbogen habe ich gelesen und verstanden. Ich konnte im Aufklärungsgespräch alle mich interessierenden Fragen stellen. Sie wurden vollständig und verständlich beantwortet. Ich fühle mich ausreichend informiert, habe mir meine Entscheidung gründlich überlegt und benötige keine weitere Überlegungsfrist.\n\nIch willige in die vorgeschlagene Behandlung ein.\n\nMit dem eventuellen Auftragen einer schmerzstillenden Salbe vor der Behandlung sowie mit u.U. erforderlichen Neben- und Folgemaßnahmen (z.B. Desinfektion) bin ich ebenfalls einverstanden.\n\nDen Fragebogen habe ich nach bestem Wissen ausgefüllt. Die Verhaltenshinweise werde ich beachten.\n\nIch bin bereit, die Kosten für den Eingriff und eventuelle behandlungsbedürftige Komplikationen zu übernehmen, wenn oder soweit die Krankenkasse keine Kostenerstattung leistet.",
    refusalText: "Ich willige in die vorgeschlagene Behandlung nicht ein. Ich habe den Aufklärungsbogen gelesen und verstanden.",
    plannedTreatment: "Injektion von Botulinumtoxin A.",
  },
];

